### ISSUE TITLE
Class name mismatch in holded/src/Treasury.php

### ISSUE THREAD

**Issue by rekuenkdr** [vshopes/holded#1]
The holded/src/Treasury.php class definition has the same name as holded/src/Payment.php class. 

It should be:

```class Treasury extends InvoiceApi``` 

https://github.com/vshopes/holded/blob/3e5e9132f4c4827f7b66c86e900a624ba645cbcb/src/Treasury.php#L11

**Comment by vshopes** [comment]
thank you!!
